<div id="placement-carousel" class="owl-carousel owl-theme" data-aos="fade-up" data-aos-delay="400">
  <!-- 65 Image Items -->
  <div class="item"><img src="../media/placementimg/1.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/2.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/3.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/4.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/5.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/6.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/7.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/8.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/9.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/10.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/11.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/12.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/13.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/14.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/15.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/16.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/17.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/18.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/19.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/20.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/21.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/22.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/23.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/24.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/25.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/26.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/27.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/28.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/29.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/30.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/31.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/32.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/33.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/34.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/35.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/36.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/37.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/38.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/39.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/40.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/41.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/42.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/43.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/44.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/45.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/46.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/47.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/48.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/49.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/50.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/51.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/52.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/53.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/54.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/55.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/56.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/57.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/58.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/59.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/60.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/61.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/62.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/63.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/64.webp" alt=""></div>
  <div class="item"><img src="../media/placementimg/65.webp" alt=""></div>
</div>
